[profile.default]
src = "contracts/src"
out = "contracts/out"
lib_paths = ["contracts/lib"]
solc_version = "0.8.20"

[etherscan]
mezo-testnet = { key = "${MEZO_EXPLORER_API_KEY}", url = "https://explorer.test.mezo.org/api" }
