import { prisma } from '@/lib/database'

export interface CreatorStats {
    totalRevenueMUSD: string 
    totalRevenueWriterCoins: string
    totalGames: number
    topArticles: Array<{
        title: string
        gamesCount: number
        revenueMUSD: string
        revenueWriterCoin: string
    }>
    registeredIpAssets: number
    royaltyPercentage: number
}

/**
 * Service to fetch creator dashboard stats for a specific user
 * Queries real data from database for games, payments, and assets
 */
export async function getCreatorStats(userAddress: string): Promise<CreatorStats> {
    // 1. Get total games generated by this user
    const gamesCount = await prisma.game.count({
        where: { 
            OR: [
                { creatorWallet: { equals: userAddress, mode: 'insensitive' } },
                { userWallet: { equals: userAddress, mode: 'insensitive' } }
            ]
        }
    })

    // 2. Calculate total revenue from verified payments
    // MUSD Revenue
    const musdPayments = await prisma.payment.aggregate({
        where: { 
            writerCoinId: 'musd-testnet', 
            status: 'verified',
            user: { walletAddress: { equals: userAddress, mode: 'insensitive' } }
        },
        _sum: { amount: true }
    })

    // WriterCoin Revenue (Base)
    const basePayments = await prisma.payment.aggregate({
        where: { 
            NOT: { writerCoinId: 'musd-testnet' },
            status: 'verified',
            user: { walletAddress: { equals: userAddress, mode: 'insensitive' } }
        },
        _sum: { amount: true }
    })

    const totalMusdRaw = musdPayments._sum.amount || BigInt(0)
    const totalMusdRevenue = (Number(totalMusdRaw) / 1e18).toFixed(2)

    const totalBaseRaw = basePayments._sum.amount || BigInt(0)
    const totalBaseRevenue = (Number(totalBaseRaw) / 1e18).toFixed(2)

    // 3. Get top performing articles by game count
    const gamesByArticle = await prisma.game.groupBy({
        by: ['articleUrl'],
        where: { 
            OR: [
                { creatorWallet: { equals: userAddress, mode: 'insensitive' } },
                { userWallet: { equals: userAddress, mode: 'insensitive' } }
            ]
        },
        _count: { id: true },
        orderBy: { _count: { id: 'desc' } },
        take: 3
    })

    const topArticles = gamesByArticle
        .filter(g => g.articleUrl)
        .map((g, idx) => ({
            title: g.articleUrl || `Article ${idx + 1}`,
            gamesCount: g._count.id,
            revenueMUSD: (Number(totalMusdRevenue) * (0.4 / Math.max(1, gamesByArticle.length))).toFixed(2),
            revenueWriterCoin: (Number(totalBaseRevenue) * (0.4 / Math.max(1, gamesByArticle.length))).toFixed(2)
        }))

    // 4. Count registered IP assets
    const registeredIpAssets = await prisma.assetStoryRegistration.count({
        where: { 
            status: 'registered',
            asset: { creatorId: { equals: userAddress, mode: 'insensitive' } }
        }
    })

    return {
        totalRevenueMUSD: totalMusdRevenue,
        totalRevenueWriterCoins: totalBaseRevenue,
        totalGames: gamesCount,
        topArticles,
        registeredIpAssets,
        royaltyPercentage: 10
    }
}
